### ISSUE TITLE
pytest vs ipdb

### ISSUE THREAD

**Issue by DavidWolff218** [learn-co-curriculum/python-p3-mapping-database-records-to-python-objects#4]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/mapping-database-records-to-python-objects?module_item_id=468023

### Concern

![Screen Shot 2023-01-02 at 12 58 41 PM](https://user-images.githubusercontent.com/60520496/210270082-f2a9853e-cf35-45b6-b28c-e458ed357999.png)
![Screen Shot 2023-01-02 at 1 00 32 PM](https://user-images.githubusercontent.com/60520496/210270113-a95ea010-117b-46ad-a23f-7bd5be9c92f4.png)

The readme shows different code than what the actual code we work with is. I think I ran into an issue bc of this when I tried to run python debug.py a second time bc I am now getting this error "sqlite3.OperationalError: unable to open database file"

**Comment by professor-ben** [comment]
I switched this to `ipdb` and changed the location of the database file so that it makes a little more sense. Let me know what you think!

-Ben
